steps:
  # Build the container image with build args
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=https://ylplopmkbairimcwdbim.supabase.co'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlscGxvcG1rYmFpcmltY3dkYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDY5Nzc2MjcsImV4cCI6MjAyMjU1MzYyN30.Ho-HINIVmBju-vQjzoUKyA_cf2wllcu'
      - '-t'
      - 'gcr.io/$PROJECT_ID/beauty-marketplace'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/beauty-marketplace']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'beauty-marketplace-new'
    - '--image'
    - 'gcr.io/$PROJECT_ID/beauty-marketplace'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_SUPABASE_URL=https://ylplopmkbairimcwdbim.supabase.co,NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlscGxvcG1rYmFpcmltY3dkYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDY5Nzc2MjcsImV4cCI6MjAyMjU1MzYyN30.Ho-HINIVmBju-vQjzoUKyA_cf2wllcu'

options:
  logging: CLOUD_LOGGING_ONLY